"""Add status to employee and employee_history table

Revision ID: 6546b215e2cd
Revises: 66dbbb46c398
Create Date: 2025-11-09 20:07:52.076065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6546b215e2cd'
down_revision: Union[str, Sequence[str], None] = '66dbbb46c398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_history', sa.Column('old_status', sa.String(length=64), nullable=True))
    op.add_column('employee_history', sa.Column('new_status', sa.String(length=64), nullable=True))
    op.add_column('employee_history', sa.Column('changed_by', sa.String(length=64), nullable=True))
    op.add_column('employee_history', sa.Column('changed_at', sa.DateTime(), nullable=True))
    op.drop_column('employee_history', 'event')
    op.drop_column('employee_history', 'event_date')
    op.add_column('employees', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'status')
    op.add_column('employee_history', sa.Column('event_date', sa.DATETIME(), nullable=True))
    op.add_column('employee_history', sa.Column('event', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('employee_history', 'changed_at')
    op.drop_column('employee_history', 'changed_by')
    op.drop_column('employee_history', 'new_status')
    op.drop_column('employee_history', 'old_status')
    # ### end Alembic commands ###
