"""Create data_issues table

Revision ID: 6c928f20e4f2
Revises: 6e8ffc4d46e8
Create Date: 2025-11-13 21:20:59.707926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c928f20e4f2'
down_revision: Union[str, Sequence[str], None] = '6e8ffc4d46e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=128), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_issues')
    # ### end Alembic commands ###
