"""Add salary to employee and validation

Revision ID: 6e8ffc4d46e8
Revises: c152c2dda79c
Create Date: 2025-11-13 21:03:12.959215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8ffc4d46e8'
down_revision: Union[str, Sequence[str], None] = 'c152c2dda79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'salary')
    # ### end Alembic commands ###
